version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_ROOT_DATABASE: admin
    volumes:
      - mongodb_data:/data/db

  birkitap:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: birkitap
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
volumes:
  mongodb_data:
